name: lelenesia_pembudidaya
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.0
  page_transition: ^1.1.6
  rxdart: ^0.24.1
  toast: ^0.1.5
  flutter_calendar_carousel: ^1.4.12
  font_awesome_flutter: ^8.9.0
  image_picker: ^0.6.7+11
  dotted_border: ^1.0.6
  flutter_session: ^0.1.1
  progress_dialog: ^1.2.4
  datetime_picker_formfield: ^1.0.0
  equatable: ^1.2.5
  dio: ^3.0.10
  flutter_icons: ^1.1.0
  intl: ^0.16.1
  charts_flutter: ^0.9.0
  flutter_statusbarcolor: ^0.2.3
  sqflite: ^1.3.0
  path_provider: ^1.6.24
  shimmer: ^1.1.2
  date_range_picker: ^1.0.6
  dropdown_search: ^0.4.8
  google_maps_flutter: ^1.0.6
  flutter_boxicons: ^2.0.1
  expandable: ^4.1.4
  table_calendar: ^2.3.3
  geolocation: ^1.1.2
  geocoder: ^0.2.1
  flutter_countdown_timer: ^3.0.0
  flutter_launcher_icons: ^0.7.0
  flutter_plugin_android_lifecycle: ^1.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
    ios: true
    android: true
    image_path_ios: "assets/logo/logo.png"
    image_path_android: "assets/logo/logo.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The followissng section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/svg/login/liquidright.svg
    - assets/svg/login/liquidleft.svg
    - assets/svg/logo_placeholder.svg
    - assets/svg/img_logo_white.svg
    - assets/svg/google_icon.svg
    - assets/svg/detail.svg
    - assets/svg/fishing.svg
    - assets/svg/
    - assets/png/
    - assets/menu/
    - assets/menu/lele.png
    - assets/menu/bandeng.png
    - assets/menu/mas.png
    - assets/menu/nila.png
    - assets/menu/patin.png
    - assets/png/ikan_mas.png
    - assets/png/ikan_nila.png
  # To add assetss to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: poppins
      fonts:
        - asset: assets/font/poppinsregular.ttf
        - asset: assets/font/poppinsbold.ttf
          weight: 700
        - asset: assets/font/poppinslight.ttf
          weight: 300
    - family: lato
      fonts:
        - asset: assets/font/latoregular.ttf
        - asset: assets/font/latobold.ttf
          weight: 700
        - asset: assets/font/latolight.ttf
          weight: 300
        - asset: assets/font/latoitalic.ttf
          style: italic
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
